apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kcs
  namespace: kcs
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - host: kcs.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 7100
          - path: /
            pathType: Prefix
            backend:
              service:
                name: marketing
                port:
                  number: 7000
    - host: ops.kcs.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ops
                port:
                  number: 7002
    - host: dev.kcs.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev
                port:
                  number: 7003
    - host: select.kcs.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: select
                port:
                  number: 7004
    - host: legacy.kcs.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 7001
