apiVersion: v1
kind: Secret
metadata:
  name: kcs-api
  namespace: kcs
type: Opaque
stringData:
  postgres-password: change-me
  database-url: postgres://kcs:change-me@postgres:5432/kcs
  s3-access-key: kcsminio
  s3-secret-key: change-me-too
