/**
 * HTTP contract the blackbox SPEC-MAP should bind to.
 * Status: 401 unauthenticated, 403 forbidden, 404 hidden/missing, 409 conflict, 400 invalid, 200/201 ok.
 */
export const API = {
  health: { method: 'GET', path: '/api/health', auth: false },
  openapi: { method: 'GET', path: '/api/openapi.json', auth: false },
  /**
   * Identity is TinyShip (better-auth) — sign-in / sign-out happen on the
   * workspace app's own `/api/auth/*`. The API only introspects the session
   * token it receives and returns the KCS role.
   */
  me: { method: 'GET', path: '/api/auth/me', auth: true },
  opsOverview: { method: 'GET', path: '/api/ops/overview', perm: 'ops.read' },
  opsCreators: { method: 'GET', path: '/api/ops/creators', perm: 'ops.read' },
  opsCreatorCreate: { method: 'POST', path: '/api/ops/creators', perm: 'ops.write' },
  opsCreatorGet: { method: 'GET', path: '/api/ops/creators/:id', perm: 'ops.read' },
  opsCreatorPatch: { method: 'PATCH', path: '/api/ops/creators/:id', perm: 'ops.write' },
  opsPublish: { method: 'POST', path: '/api/ops/creators/:id/publish', perm: 'ops.publish' },
  opsUnpublish: { method: 'POST', path: '/api/ops/creators/:id/unpublish', perm: 'ops.publish' },
  opsCategories: { method: 'GET', path: '/api/ops/categories', perm: 'ops.read' },
  opsCategoryPatch: { method: 'PATCH', path: '/api/ops/categories/:slug', perm: 'ops.categories' },
  opsReview: { method: 'GET', path: '/api/ops/review', perm: 'ops.read' },
  opsReviewPass: { method: 'POST', path: '/api/ops/review/:id/pass', perm: 'ops.write' },
  opsBatches: { method: 'GET', path: '/api/ops/batches', perm: 'ops.read' },
  opsBatchUpload: { method: 'POST', path: '/api/ops/batches', perm: 'ops.write' },
  pool: { method: 'GET', path: '/api/select/pool', perm: 'select.read' },
  queries: { method: 'GET', path: '/api/select/queries', perm: 'select.read' },
  queryCreate: { method: 'POST', path: '/api/select/queries', perm: 'select.write' },
  queryGet: { method: 'GET', path: '/api/select/queries/:id', perm: 'select.read' },
  queryPatch: { method: 'PATCH', path: '/api/select/queries/:id', perm: 'select.write' },
  queryDelete: { method: 'DELETE', path: '/api/select/queries/:id', perm: 'select.write' },
  queryRun: { method: 'POST', path: '/api/select/queries/run', perm: 'select.read' },
  metricsPublic: { method: 'GET', path: '/api/metrics/fields', auth: false },
  poolCreator: { method: 'GET', path: '/api/select/creators/:id', perm: 'select.read' },
  poolCreatorHistory: { method: 'GET', path: '/api/select/creators/:id/history', perm: 'select.read' },
  projects: { method: 'GET', path: '/api/select/projects', perm: 'select.read' },
  projectCreate: { method: 'POST', path: '/api/select/projects', perm: 'select.write' },
  projectGet: { method: 'GET', path: '/api/select/projects/:id', perm: 'select.read' },
  assign: { method: 'POST', path: '/api/select/projects/:id/assignments', perm: 'select.assign' },
  unassign: { method: 'DELETE', path: '/api/select/projects/:id/assignments/:creatorId', perm: 'select.assign' },
  shortlist: { method: 'GET', path: '/api/select/shortlist', perm: 'select.read' },
  shortlistAdd: { method: 'POST', path: '/api/select/shortlist', perm: 'select.write' },
  exportProject: { method: 'GET', path: '/api/select/projects/:id/export', perm: 'select.read' },
  devHealth: { method: 'GET', path: '/api/dev/health', perm: 'dev.read' },
  devJobs: { method: 'GET', path: '/api/dev/jobs', perm: 'dev.read' },
  devJob: { method: 'GET', path: '/api/dev/jobs/:id', perm: 'dev.read' },
  devRetry: { method: 'POST', path: '/api/dev/jobs/:id/retry', perm: 'dev.retry' },
  devFailures: { method: 'GET', path: '/api/dev/failures', perm: 'dev.read' },
  devPipeline: { method: 'GET', path: '/api/dev/pipeline', perm: 'dev.read' },
  devAudit: { method: 'GET', path: '/api/dev/audit', perm: 'dev.read' },
  devI18n: { method: 'GET', path: '/api/dev/i18n-theme', perm: 'dev.read' },
  ingestSources: { method: 'GET', path: '/api/ingest/sources', perm: 'ingest.read' },
  ingestAdapters: { method: 'GET', path: '/api/ingest/adapters', perm: 'ingest.read' },
  ingestFetch: { method: 'POST', path: '/api/ingest/fetch', perm: 'ingest.write' },
  ingestRaw: { method: 'GET', path: '/api/ingest/raw/:creatorId', perm: 'ingest.read' },
  ingestJobs: { method: 'GET', path: '/api/ingest/jobs', perm: 'ingest.read' },
  ingestJobCreate: { method: 'POST', path: '/api/ingest/jobs', perm: 'ingest.write' },
  ingestJob: { method: 'GET', path: '/api/ingest/jobs/:id', perm: 'ingest.read' },
  ingestSample: { method: 'GET', path: '/api/ingest/jobs/:id/sample', perm: 'ingest.read' },
  ingestJobRetry: { method: 'POST', path: '/api/ingest/jobs/:id/retry', perm: 'ingest.retry' },
  ingestJobCancel: { method: 'POST', path: '/api/ingest/jobs/:id/cancel', perm: 'ingest.write' },
  presign: { method: 'POST', path: '/api/assets/presign', perm: 'ops.write' },
} as const
