export const MOCKUP_IDS = [
  'A-login',
  'A-home',
  'A-batch-upload',
  'A-batch-list',
  'A-batch-clean',
  'A-creator-form',
  'A-creator-qc',
  'A-score-preview',
  'A-ai-queue',
  'A-ai-detail',
  'A-human-label',
  'A-publish',
  'B-health',
  'B-jobs',
  'B-failures',
  'B-pipeline',
  'B-audit',
  'B-i18n-theme',
  'C-login',
  'C-projects',
  'C-project-new',
  'C-project-board',
  'C-pool',
  'C-creator',
  'C-shortlist',
  'C-assign',
  'C-export',
] as const

export type MockupId = (typeof MOCKUP_IDS)[number]

const PATHS: Record<MockupId, string> = {
  'A-login': '/login',
  'A-home': '/ops',
  'A-batch-upload': '/ops/batches/upload',
  'A-batch-list': '/ops/batches',
  'A-batch-clean': '/ops/batches/:id',
  'A-creator-form': '/ops/creators/new',
  'A-creator-qc': '/ops/qc',
  'A-score-preview': '/ops/rating',
  'A-ai-queue': '/ops/review',
  'A-ai-detail': '/ops/review/:id',
  'A-human-label': '/ops/label',
  'A-publish': '/ops/publish',
  'B-health': '/dev',
  'B-jobs': '/dev/jobs',
  'B-failures': '/dev/failures',
  'B-pipeline': '/dev/pipeline',
  'B-audit': '/dev/audit',
  'B-i18n-theme': '/dev/i18n-theme',
  'C-login': '/login',
  'C-projects': '/select',
  'C-project-new': '/select/projects/new',
  'C-project-board': '/select/projects/:id',
  'C-pool': '/select/pool',
  'C-creator': '/select/creators/:id',
  'C-shortlist': '/select/shortlist',
  'C-assign': '/select/assign',
  'C-export': '/select/export',
}

export function screenPath(id: MockupId): string {
  return PATHS[id]
}

export const SCREEN_TESTID: Record<MockupId, string> = {
  'A-login': 'screen-a-login',
  'A-home': 'screen-a-home',
  'A-batch-upload': 'screen-a-batch-upload',
  'A-batch-list': 'screen-a-batch-list',
  'A-batch-clean': 'screen-a-batch-clean',
  'A-creator-form': 'screen-a-creator-form',
  'A-creator-qc': 'screen-a-creator-qc',
  'A-score-preview': 'screen-a-score-preview',
  'A-ai-queue': 'screen-a-ai-queue',
  'A-ai-detail': 'screen-a-ai-detail',
  'A-human-label': 'screen-a-human-label',
  'A-publish': 'screen-a-publish',
  'B-health': 'screen-b-health',
  'B-jobs': 'screen-b-jobs',
  'B-failures': 'screen-b-failures',
  'B-pipeline': 'screen-b-pipeline',
  'B-audit': 'screen-b-audit',
  'B-i18n-theme': 'screen-b-i18n-theme',
  'C-login': 'screen-c-login',
  'C-projects': 'screen-c-projects',
  'C-project-new': 'screen-c-project-new',
  'C-project-board': 'screen-c-project-board',
  'C-pool': 'screen-c-pool',
  'C-creator': 'screen-c-creator',
  'C-shortlist': 'screen-c-shortlist',
  'C-assign': 'screen-c-assign',
  'C-export': 'screen-c-export',
}
