export const TESTID = {
  localeSwitch: 'locale-switch',
  themeToggle: 'theme-toggle',
  loginEmail: 'login-email',
  loginPassword: 'login-password',
  loginSubmit: 'login-submit',
  loginError: 'login-error',
  navOps: 'nav-ops',
  navDev: 'nav-dev',
  navSelect: 'nav-select',
  navIngest: 'nav-ingest',
  btnPublish: 'btn-publish',
  btnAssign: 'btn-assign',
  btnCreateProject: 'btn-create-project',
  btnCreateCreator: 'btn-create-creator',
  btnRetryJob: 'btn-retry-job',
  filterTier: 'filter-tier',
  filterHealth: 'filter-health',
  queryBar: 'query-bar',
  sortKey: 'sort-key',
  filterCategories: 'filter-categories',
  tablePool: 'table-pool',
  tableProjects: 'table-projects',
  tableJobs: 'table-jobs',
  denied: 'screen-denied',
} as const
