import { SCREEN_TESTID, TESTID } from '../../packages/kcs-contract/src/index.ts';

/** Official TESTID plus journey extras. Extra ids are listed in e2e/CONTRACT.md. */
export const tid = {
  ...TESTID,
  screen: SCREEN_TESTID,
  session: 'auth-session',
  displayName: 'creator-display-name',
  followers: 'creator-followers',
  priceMin: 'creator-price-min',
  avatar: 'creator-avatar',
  avatarUrl: 'creator-avatar-url',
  categoryCollaborated: 'category-collaborated',
  categoryNever: 'category-never-collaborated',
  save: 'btn-save-creator',
  publishConfirm: 'btn-publish-confirm',
  creatorStatus: 'creator-status',
  creatorKey: 'creator-key',
  projectName: 'project-name',
  libraryOpen: 'btn-open-library',
  filterFollowersMin: 'filter-followers-min',
  filterFollowersMax: 'filter-followers-max',
  filterPriceMin: 'filter-price-min',
  filterPriceMax: 'filter-price-max',
  sortFollowers: 'sort-followers',
  sortPrice: 'sort-price',
  sortCollab: 'sort-collab',
  libraryRow: 'row-pool',
  libraryCheckbox: 'row-pool-check',
  assignConfirm: 'btn-assign-confirm',
  projectRow: 'row-project-assignment',
  jobCount: 'dev-job-count',
  sqlOk: 'dev-sql-ok',
} as const;
