import { SCREEN_TESTID, TESTID } from '../../packages/kcs-contract/src/index.ts';

/** Official TESTID plus journey extras. Extra ids are listed in e2e/CONTRACT.md. */
export const tid = {
  ...TESTID,
  screen: SCREEN_TESTID,
  session: 'auth-session',
  displayName: 'creator-display-name',
  followers: 'creator-followers',
  priceMin: 'creator-price-min',
  avatar: 'creator-avatar',
  avatarUrl: 'creator-avatar-url',
  categoryCollaborated: 'category-collaborated',
  categoryNever: 'category-never-collaborated',
  save: 'btn-save-creator',
  publishConfirm: 'btn-publish-confirm',
  creatorStatus: 'creator-status',
  creatorKey: 'creator-key',
  projectName: 'project-name',
  libraryOpen: 'btn-open-library',
  queryBar: 'query-bar',
  queryEditorToggle: 'query-editor-toggle',
  queryEditor: 'query-editor',
  queryAddFilter: 'query-add-filter',
  filterTierMid: 'filter-tier-mid',
  filterHealthExcellent: 'filter-health-excellent',
  poolSearch: 'pool-search',
  poolCount: 'pool-count',
  sortKey: 'sort-key',
  sortDir: 'sort-dir',
  libraryRow: 'row-pool',
  libraryCheckbox: 'row-pool-check',
  assignConfirm: 'btn-assign-confirm',
  projectRow: 'row-project-assignment',
  jobCount: 'dev-job-count',
  sqlOk: 'dev-sql-ok',
} as const;
